{ status: 200,
  statusText: 'OK',
  headers:
   { date: 'Fri, 31 Mar 2017 00:30:01 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '7634',
     connection: 'close',
     server: 'nginx',
     'x-yummly-request-id': '13bcb0cd-5978-47c7-914c-63fc6959cc9d' },
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.15.3' },
     method: 'get',
     url: 'http://api.yummly.com/v1/api/recipes?_app_id=aa394476&_app_key=cd86d4e0e848d722a9fc99cc024b7aab&q=cake%2B&allowedIngredient%5B%5D=chocolate&excludedIngredient%5B%5D=carrots&allowedAllergy%5B%5D=393%5EGluten-Free&',
     data: undefined },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events:
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { maxRedirects: 21,
        protocol: 'http:',
        hostname: 'api.yummly.com',
        port: null,
        path: '/v1/api/recipes?_app_id=aa394476&_app_key=cd86d4e0e848d722a9fc99cc024b7aab&q=cake%2B&allowedIngredient%5B%5D=chocolate&excludedIngredient%5B%5D=carrots&allowedAllergy%5B%5D=393%5EGluten-Free&',
        method: 'get',
        headers: [Object],
        agent: undefined,
        auth: undefined },
     _redirectCount: 0,
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /v1/api/recipes?_app_id=aa394476&_app_key=cd86d4e0e848d722a9fc99cc024b7aab&q=cake%2B&allowedIngredient%5B%5D=chocolate&excludedIngredient%5B%5D=carrots&allowedAllergy%5B%5D=393%5EGluten-Free& HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.15.3\r\nHost: api.yummly.com\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/v1/api/recipes?_app_id=aa394476&_app_key=cd86d4e0e848d722a9fc99cc024b7aab&q=cake%2B&allowedIngredient%5B%5D=chocolate&excludedIngredient%5B%5D=carrots&allowedAllergy%5B%5D=393%5EGluten-Free&',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular] },
     _currentUrl: 'http://api.yummly.com' },
  data:
   { criteria:
      { q: 'cake+',
        allowedIngredient: [Object],
        excludedIngredient: [Object],
        allowedAllergy: [Object] },
     matches:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     facetCounts: {},
     totalMatchCount: 5005,
     attribution:
      { html: 'Recipe search powered by <a href=\'http://www.yummly.co/recipes\'><img alt=\'Yummly\' src=\'https://static.yummly.co/api-logo.png\'/></a>',
        url: 'http://www.yummly.co/recipes/',
        text: 'Recipe search powered by Yummly',
        logo: 'https://static.yummly.co/api-logo.png' } } }